/**
 * Created by victorjose.gallego on 2/4/16.
 */

export const TYPES = {
	TEMPLATE_TYPE : Symbol('TEMPLATE_TYPE'),
	CHANGE_TASK_WORKFLOW_STATE : Symbol('CHANGE_TASK_WORKFLOW_STATE'),
	ADD_DELETE_WORKFLOW_TO_WORKFLOW_TEMPLATE : Symbol('ADD_DELETE_WORKFLOW_TO_WORKFLOW_TEMPLATE'),
	CHANGE_TIME_WINDOW : Symbol('CHANGE_TIME_WINDOW'),
	DELETE_DATA : Symbol('DELETE_DATA'),
	MODIFY_ERRORS : Symbol('MODIFY_ERRORS'),
	CHANGE_SUGESTION_LIST : Symbol('CHANGE_SUGESTION_LIST'),
	ADD_DELETE_TASK_TO_TASK_TEMPLATE : Symbol('ADD_DELETE_TASK_TO_TASK_TEMPLATE'),
}

export default TYPES;