/**
 * Created by victorjose.gallego on 2/4/16.
 */

export const TYPES = {
	TEMPLATE_TYPE : Symbol('TEMPLATE_TYPE'),
	SET_WORKFLOW_SUGESTION : Symbol('SET_WORKFLOW_SUGESTION'),
	CHANGE_WORKFLOW_VISIBILITY : Symbol('CHANGE_WORKFLOW_VISIBILITY'),
	CHANGE_WORKFLOW_STATE : Symbol('CHANGE_WORKFLOW_STATE'),
	ADD_DELETE_WORKFLOW_TO_WORKFLOW_TEMPLATE : Symbol('ADD_DELETE_WORKFLOW_TO_WORKFLOW_TEMPLATE'),
	CHANGE_TIME_WINDOW : Symbol('CHANGE_TIME_WINDOW'),
}

export default TYPES;