/**
 * Created by victorjose.gallego on 2/4/16.
 */

 export const TYPES = {
	CONTINUE_STEP: Symbol('CONTINUE_STEP'),
	SELECT_STEP: Symbol('SELECT_STEP'),
	NAME_CHANGE: Symbol('NAME_CHANGE'),
	KEYWORDS_CHANGE: Symbol('KEYWORDS_CHANGE'),
	DESCRIPTION_CHANGE: Symbol('DESCRIPTION_CHANGE'),
	TIME_CHANGE: Symbol('TIME_CHANGE'),
	CODE_CHANGE: Symbol('CODE_CHANGE'),
	DELETE_DATA: Symbol('DELETE_DATA'),
	ADD_DATA: Symbol('ADD_DATA'),
	REPRESENTATION_TYPE_CHANGE: Symbol('REPRESENTATION_TYPE_CHANGE'),
	MAP_XAXYS_CHANGE: Symbol('MAP_XAXYS_CHANGE'),
	MAP_YAXYS_CHANGE: Symbol('MAP_YAXYS_CHANGE'),
	LABEL_XAXYS_CHANGE: Symbol('LABEL_XAXYS_CHANGE'),
	LABEL_YAXYS_CHANGE: Symbol('LABEL_YAXYS_CHANGE'),
	TOGGLE_REPRESENTATION_NEW_OR_EDIT: Symbol('TOGGLE_REPRESENTATION_NEW_OR_EDIT'),
	ADD_REPRESENTATION_TO_EDIT: Symbol('ADD_REPRESENTATION_TO_EDIT'),
	ADD_REPRESENTATION_TO_NEW: Symbol('ADD_REPRESENTATION_TO_NEW'),
	ADD_DELETE_REPRESENTATION_TO_KPI: Symbol('ADD_DELETE_REPRESENTATION_TO_KPI'),
	MODIFY_ERRORS: Symbol('MODIFY_ERRORS'),
	IFRAME_ONCE_LOAD: Symbol('IFRAME_ONCE_LOAD'),
	SET_PROPERTIES: Symbol('SET_PROPERTIES'),
}

export default TYPES;