language: scala
os:
  - linux
  - osx
scala:
  - 2.11.7
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
notifications:
  email:
    - masgui@gmail.com
script:
  - sbt -J-XX:ReservedCodeCacheSize=256M test
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
matrix:
  exclude:
    # no jdk switcher
    - os: osx